### ISSUE TITLE
Diseño 

### ISSUE THREAD

**Issue by garaziAlfaro** [pfernandezferna1993/AIVA_MUVA_DefectosMetales#7]
- [x] #10 Diagrama UML de  Clases.
- [x] #11 Diagrama UML de Secuencia.
- [x] #12 Diagrama UML de Actividad.
- [x] #13 Desarrollo de los principales algoritmos.
- [x] #14 README.md del proyecto.
- [x] #15 Sección de "Introducción" al desarrollo realizado. 
- [x] #16 Completar test unitarios para el desarrollo.
